name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"  # Esegue ogni giorno alle 18:00 UTC (19:00 IT)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permette il push
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_PRIVATE_TOKEN }}  # Usa il PAT per il checkout
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PRIVATE_TOKEN }}  # Usa il PAT per i dati privati
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "Update 3D contribution graph"; then
            git push
          fi
