name: GitHub-Profile-3D-Contrib

on:
  schedule:  # Esegue automaticamente ogni giorno alle 18:00 UTC (19:00 in Italia)
    - cron: "0 18 * * *"
  workflow_dispatch:  # Permette di eseguirlo manualmente da GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Dà al token i permessi per fare push
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "generated"; then
            git push
          fi
